# Generated by Django 4.1.5 on 2023-01-15 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moneybook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyBookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_id", models.IntegerField()),
                (
                    "cash",
                    models.IntegerField(
                        default=0,
                        help_text="수입/지출 금액",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "log_status",
                    models.CharField(
                        choices=[("IC", "Income"), ("EP", "Expense")], max_length=2
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moneybook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moneybook.moneybook",
                    ),
                ),
            ],
        ),
    ]
